name: Build LaTeX + Catalog

on:
  push:
    paths:
      - 'latex/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-lang-french texlive-science

      - run: |
          mkdir -p pdfs
          mkdir -p data

          echo "[" > data/catalog.json
          first=1

          for dir in latex/*; do
            if [ -f "$dir/main.tex" ]; then

              name=$(basename $dir)

              cd $dir
              pdflatex main.tex
              cd -

              cp $dir/main.pdf pdfs/$name.pdf

              if [ $first -eq 0 ]; then echo "," >> data/catalog.json; fi
              first=0

              echo "{\"titre\":\"$name\",\"pdf\":\"pdfs/$name.pdf\"}" >> data/catalog.json
            fi
          done

          echo "]" >> data/catalog.json

      - run: |
          git config user.name "bot"
          git config user.email "bot@mail.com"
          git add pdfs data/catalog.json
          git commit -m "auto build" || echo "no change"
          git push
